apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "390940956173934"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "c8970a41-5231-47b5-b0f9-0b6ee2af03f2"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "3b3574c919ec418ea992a5931606c31e"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
